# Ship a minimal metadata file that can be picked up by Streamlit at runtime.
[project]
name = "streamlit-dateinput-intl"
version = "0.0.1"

[[tool.streamlit.component.components]]
name = "streamlit_dateinput_intl"
asset_dir = "frontend/build"
